'use client';

import { useState } from 'react';
import { useTamboThread, useTamboThreadInput } from '@tambo-ai/react';

export default function GeneratePage() {
    const { thread } = useTamboThread();
    const { value, setValue, submit, isPending } = useTamboThreadInput();
    const [saveStatus, setSaveStatus] = useState<{
        loading: boolean;
        success: boolean;
        error: string | null;
        data: any;
    }>({ loading: false, success: false, error: null, data: null });

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        // Append instruction to ensure decisive generation
        const enhancedPrompt = `${value} . IMPORTANT: Generate comprehensive content with realistic placeholders for all fields (address, email, phone, etc). Do not ask follow-up questions.`;
        setValue(enhancedPrompt);
        // Allow state to update before submitting
        setTimeout(() => submit(), 0);
    };

    const handleSaveToDatabase = async () => {
        setSaveStatus({ loading: true, success: false, error: null, data: null });

        try {
            // Get the generated data from the last message
            const lastMessage = thread.messages[thread.messages.length - 1];
            // Extract sections from Tambo messages
            const sections = thread.messages
                .filter((msg: any) => msg.role === 'assistant' && msg.component && msg.component.componentName)
                .map((msg: any, index: number) => ({
                    id: `section_${Date.now()}_${index}`,
                    type: msg.component.componentName.toLowerCase(),
                    title: msg.component.componentName,
                    content: msg.component.props || {},
                    order: index,
                }));

            // Smart Title Generation
            let generatedTitle = 'Untitled Website';

            // 1. Try to get title from Hero heading
            const heroSection = sections.find((s: any) => s.type === 'hero');
            if (heroSection && heroSection.content && heroSection.content.heading) {
                generatedTitle = heroSection.content.heading;
            }
            // 2. Fallback to extracting from prompt
            else if (value) {
                // Remove command words and "enhanced" suffix
                const cleanPrompt = value.split('.')[0] // Take first sentence/part before injected instruction
                    .replace(/create a |make a |generate a |website for |website/gi, '')
                    .trim();

                if (cleanPrompt) {
                    generatedTitle = cleanPrompt.charAt(0).toUpperCase() + cleanPrompt.slice(1);
                }
            }

            const websiteData = {
                title: generatedTitle,
                description: 'Generated by Tambo AI',
                theme: {
                    name: 'Default Theme',
                    colors: {
                        primary: '#3B82F6',
                        primaryDark: '#1E40AF',
                        primaryLight: '#60A5FA',
                        background: '#FFFFFF',
                        backgroundAlt: '#F9FAFB',
                        backgroundLight: '#F3F4F6',
                        text: '#1F2937',
                        textLight: '#6B7280',
                        textDark: '#111827',
                        accent: '#10B981',
                        success: '#10B981',
                        warning: '#F59E0B',
                        error: '#EF4444',
                    },
                },
                sections: sections,
            };

            console.log('Website Data to be saved:', JSON.stringify(websiteData, null, 2));

            // Get auth token from localStorage
            const token = localStorage.getItem('token');

            const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/websites/generate`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${token}`,
                },
                body: JSON.stringify(websiteData),
            });

            if (!response.ok) {
                const error = await response.json();
                throw new Error(error.message || 'Failed to save website');
            }

            const data = await response.json();
            setSaveStatus({ loading: false, success: true, error: null, data: data.data });
        } catch (error: any) {
            setSaveStatus({ loading: false, success: false, error: error.message, data: null });
        }
    };

    return (
        <div className="min-h-screen bg-gray-50 p-8">
            <div className="max-w-6xl mx-auto">
                <h1 className="text-4xl font-bold mb-8">Generate Website with AI</h1>

                {/* Chat Interface */}
                <div className="bg-white rounded-lg shadow-md p-6 mb-6">
                    <div className="mb-6 h-96 overflow-y-auto border border-gray-200 rounded-lg p-4">
                        {thread.messages.map((message) => (
                            <div
                                key={message.id}
                                className={`mb-4 p-3 rounded-lg ${message.role === 'user'
                                    ? 'bg-blue-100 ml-auto max-w-md'
                                    : 'bg-gray-100 mr-auto max-w-md'
                                    }`}
                            >
                                <div className="font-semibold text-sm mb-1">
                                    {message.role === 'user' ? 'You' : 'Tambo AI'}
                                </div>
                                {Array.isArray(message.content) ? (
                                    message.content.map((part, i) =>
                                        part.type === 'text' ? (
                                            <p key={i} className="text-gray-800">
                                                {part.text}
                                            </p>
                                        ) : null
                                    )
                                ) : (
                                    <p className="text-gray-800">{String(message.content)}</p>
                                )}
                                {message.renderedComponent && (
                                    <div className="mt-2 border-t pt-2">
                                        {message.renderedComponent}
                                    </div>
                                )}
                            </div>
                        ))}
                        {isPending && (
                            <div className="text-gray-500 italic">AI is thinking...</div>
                        )}
                    </div>

                    <form onSubmit={handleSubmit} className="flex gap-2">
                        <input
                            type="text"
                            value={value}
                            onChange={(e) => setValue(e.target.value)}
                            placeholder="Describe your website (e.g., 'make an education website')"
                            className="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                            disabled={isPending}
                        />
                        <button
                            type="submit"
                            disabled={isPending || !value.trim()}
                            className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:bg-gray-400 disabled:cursor-not-allowed"
                        >
                            {isPending ? 'Generating...' : 'Generate'}
                        </button>
                    </form>
                </div>

                {/* Save to Database */}
                {thread.messages.length > 0 && (
                    <div className="bg-white rounded-lg shadow-md p-6">
                        <h2 className="text-2xl font-bold mb-4">Save Website</h2>
                        <p className="text-gray-600 mb-4">
                            Save the generated website to your dashboard
                        </p>

                        <button
                            onClick={handleSaveToDatabase}
                            disabled={saveStatus.loading}
                            className="px-6 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 disabled:bg-gray-400 disabled:cursor-not-allowed"
                        >
                            {saveStatus.loading ? 'Saving...' : 'Save to Database'}
                        </button>

                        {saveStatus.success && (
                            <div className="mt-4 p-4 bg-green-100 border border-green-400 rounded-lg">
                                <p className="text-green-800 font-semibold">
                                    ✅ Website saved successfully!
                                </p>
                                <p className="text-green-700 mt-2">
                                    Page ID: {saveStatus.data?.pageId}
                                </p>
                                <p className="text-green-700">
                                    Slug: {saveStatus.data?.slug}
                                </p>
                                <a
                                    href={`/dashboard`}
                                    className="inline-block mt-2 text-green-800 underline"
                                >
                                    View in Dashboard →
                                </a>
                            </div>
                        )}

                        {saveStatus.error && (
                            <div className="mt-4 p-4 bg-red-100 border border-red-400 rounded-lg">
                                <p className="text-red-800">❌ Error: {saveStatus.error}</p>
                            </div>
                        )}
                    </div>
                )}
            </div>
        </div>
    );
}
